[phases.setup]
aptPkgs = ["libvips-dev"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npm install", "npx prisma generate"]

[phases.deploy]
cmds = ["npx prisma db push --accept-data-loss"]

[start]
cmd = "npm start"
