[phases.setup]
aptPkgs = ["libvips-dev"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npm install", "npx prisma generate", "npx prisma migrate deploy"]

[start]
cmd = "npm start"
